#!/usr/bin/env python
#-*- indent-tabs-mode: t; python-indent: 8; tab-width: 4; -*-
import os
import platform
import sys
import csv
import codecs
import datetime
from dateutil.parser import parse
import optparse
import re

currencyvar = "$"

def myNewLine():
	if platform.system() == 'Windows':
		return "\r\n"
	else:
		return "\n"

def isnumeric(value):
	global currencyvar
	return str(value).replace(",","").replace(".", "").replace("-", "").replace(currencyvar, "").strip().isdigit()

class Transaction(object):
	def __init__(self, date, text):
		self.date = date
		self.text = text

def parseCSV(fn,debitheaders,accountheaders,notef,datef):
	f = open(fn, 'rb')
	reader = csv.DictReader(f)
	transactions = []
	for item in reader:
		transactions.append(ProcessEntry(item,debitheaders,accountheaders,notef,datef))
	f.close()
	transactions = sorted(transactions, key=lambda t:t.date)
	return (myNewLine() + myNewLine()).join([t.text for t in transactions])

def checkDate(mstr):
	try:
		return parse(mstr)
	except Exception as inst:
		return datetime.date.today()

amtre = re.compile(r'({0}?)(-?)({0}?)([0-9.]*)'.format(r'\$' if currencyvar == '$' else currencyvar))

def format_amount(s, negate=False):
	s = s.strip()
	match = amtre.match(s)
	if match:
		minus_sign = '-' if bool(match.group(2)) ^ negate else ''
		return '{0}{1}{2}'.format(minus_sign, currencyvar, match.group(4))
	elif negate:
		return "(" + s + " * (-1))"
	else:
		return s

def ProcessEntry(item,dheader,accts,notefields,datef):
	accounts = []
	accounts = accts[:]
	startline = ''
	dateline = ''
	noteline = []
	
	for notef in notefields:
		if item.has_key(notef):
			noteline.append(item[notef].strip())
	if noteline == []:
		noteline = 'Transaction'
	else:
		noteline = ' '.join(noteline)
	
	if item.has_key(datef) and len(datef)>0:
		date = checkDate(item[datef])
		dateline = date.strftime('%Y/%m/%d')
	else:
		currentdate = datetime.date.today().isoformat().replace('-','/').strip()
		dateline = currentdate
	
	startline = dateline + " * " + noteline
	count = 0
	for s in dheader:		
		if item.has_key(s) and isnumeric(item[s]) and len(accounts) > count:
			accounts[count] = accounts[count] + "\t\t" + format_amount(item[s])
		elif s[0] =='-' and item.has_key(s[1:]) and isnumeric(item[s[1:]]) and len(accounts) > count:
			accounts[count] = accounts[count] + "\t\t" + format_amount(item[s[1:]], True)
		count = count+1
	transaction = startline
	for s in accounts:
		transaction = transaction + myNewLine() + "\t" + s.strip()
	return Transaction(date, transaction)

def isCSV(myfile):
	if os.path.isfile(os.path.expanduser(myfile)):
		return os.path.abspath(os.path.expanduser(myfile))
	else:
		print 'The file you specified does not exist'
		sys.exit()
		
def isReturnFile(myfile):
	if os.path.abspath(os.path.expanduser(myfile)) != False:
		return os.path.abspath(os.path.expanduser(myfile))
	else:
		print 'You can\'t save to that location'
		sys.exit()


def SaveFile(transaction,myfile):
	mf = isReturnFile(myfile)
	if os.path.isfile(mf):
		fout = codecs.open(mf, "a", "utf-8")
		fout.write(unicode(myNewLine(), "utf-8"))
	else:
		fout = codecs.open(mf, "w", "utf-8")
	fout.write(unicode(transaction,"utf-8"))
	fout.close()
	print 'Saved File!'	

def split_arg(s):
	if len(s)>0:
		return s.split(',')
	else:
		return []

def main():
	global currencyvar
	didsomething = False
	
	desc = 'This tool allows you to convert CSVs into a format appropriate for Ledger.  It\'s particularly useful when you need to specify multipart transactions.'
	p = optparse.OptionParser(description=desc)
	utilities = optparse.OptionGroup(p, 'Utility Options')
	utilities.add_option('--open', '-o', dest="openfile", help="CSV file to open", default='', metavar='"<File Path>"')
	utilities.add_option('--save', '-s', dest="savefile", help="Save output to a file", default='', metavar='"<File Path>"')
	utilities.add_option('--currency', '-c', dest="currency", help="Currency character in data", default='', metavar='"$"')
	utilities.add_option('--date', '-d', dest="datefield", help="Name of field containing transaction date", default='', metavar='"date"')
	utilities.add_option('--note', '-n', dest="notefield", help="Name of field containing transaction note", default='', metavar='"note"')
	
	accountsec = optparse.OptionGroup(p, 'Account Options')
	accountsec.add_option('--accounts','-a',dest="accounts",help="Comma separated list of accounts",default='',metavar='"Assets:Checking, Equity:Revenue"')
	accountsec.add_option('--fields','-f',dest="fields",help="Comma separated list of field names (in the CSV) to include with accounts.  Fields prepended with a \"-\" will flip the sign of the field.",default='',metavar='"payment, tax"')
	
	p.add_option_group(utilities)
	p.add_option_group(accountsec)
	(options, arguments) = p.parse_args();
	
	if len(options.currency)>0:
		currencyvar = options.currency
		
	if len(options.accounts)>0:
		laccounts = options.accounts.split(',')
	else:
		print 'No accounts specified'
		sys.exit()
	
	lfields = split_arg(options.fields)
	
	if len(options.openfile)>0:
		csvfile = isCSV(options.openfile)
	else:
		print 'You must specify a file to open'
		sys.exit()
	
	notefield = split_arg(options.notefield)
	
	transactions = parseCSV(csvfile,lfields,laccounts,notefield,options.datefield)
	
	if len(options.savefile)>0:
		SaveFile(transactions,options.savefile)
		sys.exit()
	else:
		print unicode(transactions,"utf-8")
		sys.exit()
		
if __name__ == '__main__':
	main()
